name: "Ex01"

on:
  push:
  
jobs:
  print_date_ubuntu:
    name: print date Ubuntu!
    runs-on: ubuntu-latest
    
    steps:
      - name: Hello world Ubuntu!
        run: date
        
  print_date_windows:
    name: print date Windows!
    runs-on: windows-latest
    
    steps:
      - name: Hello world Windows!
        run: date
              
  print_date_macos:
    name: print date MacOS!
    runs-on: macos-latest
    
    steps:
      - name: Hello world MacOS!
        run: date
           
    print_date_last:
      name: Print Date Last!
      runs-on: ubuntu-latest
      
    needs:
      - print_date_ubuntu
      - print_date_windows
      - print_date_macos
      
        steps:
          - name: Print Date Final!
            run: date    
